[colors.normal]
black =   '#121212'  # bg_float_bright
red =     '#9E4244'  # light_red
green =   '#F85149'  # light_orange
yellow =  '#F6ACA7'  # pink
blue =    '#B76E79'  # light_pink
magenta = '#8B2950'  # magenta
cyan =    '#B76E79'  # dark_pink
white =   '#C9C1C9'  # fg


[colors.bright]
black =   '#8B8B8B'  # gray
red =     '#FF7979'  # pink
green =   '#F6ACA7'  # light_pink
yellow =  '#F85149'  # light_red
blue =    '#C9C1C9'  # fg
magenta = '#F6ACA7'  # light_pink
cyan =    '#F6ACA7'  # light_pink
white =   '#C9C1C9'  # fg

[colors.primary]
background = "#000000"
foreground = "#abb2bf"

[font]
normal = { family = "Inconsolata Nerd Font Mono", style = "Regular" }

[window]
decorations = "None"

