
[colors.primary]
foreground = "#2a2b33"
background = "#dde6f0"

[colors.normal]
black    = "#000000"
red      = "#b6443a"
green    = "#40803f"
yellow   = "#795300"
blue     = "#3360c1"
magenta  = "#841e83"
cyan     = "#006996"
white    = "#ccccc0"

[colors.bright]
black    = "#000000"
red      = "#b6443a"
green    = "#40803f"
yellow   = "#795300"
blue     = "#3360c1"
magenta  = "#841e83"
cyan     = "#006996"
white    = "#ccccc0"

[font]
normal = { family = "MesloLGS Nerd Font Mono", style = "Regular" }

[window]
decorations = "None"

[terminal]
shell = { program = "/usr/local/bin/bash", args = ["--login"]}

